### ISSUE TITLE
about setup

### ISSUE THREAD

**Issue by coper16** [zju3dv/GIFT#8]
Hi
Thank you for your great work!

I try to train GIFT-stage1.
And, I had a error.
Do you have any idea why this happens?

![スクリーンショット 2020-12-22 13 10 09](https://user-images.githubusercontent.com/54351314/102848076-3f504200-4457-11eb-84cd-df3007fd0472.png)

**Comment by liuyuan-pal** [comment]
Thank you, it may be because your GPU is an old one? https://github.com/pytorch/pytorch/issues/31285
Maybe, you can try re-compile the hard exampling mining module.

**Comment by coper16** [comment]
Thank you for your quick reply!

I see.
I come up with anything that might have caused it.
I set up these code in local PC and I moved it to external server because l want to use many gpu.
But, GPU name is not same.

So, I compiled extend utilities in external server. 
I have this error.
Do you have any idea why this happens?

I think 
`cuda_include=f'/usr/local/cuda-10.1/include'`
`cuda_library=f'/usr/local/cuda-10.1/lib64'`
is wrong on my code because I use cudatoolkit by conda(I need to use conda environment).
but, I cannot find same .h file( in /usr/local/cuda-10.1/include or usr/local/cuda-10.1/lib64) in anaconda directory...


`
Cannot determine CUDA_HOME: cuda-gdb not in PATH
/home/nshimobayashi/anaconda3/envs/GIFT_2/bin/nvcc: line 2: /bin/nvcc: No such file or directory
x86_64-conda_cos6-linux-gnu-gcc: error: src/nearest_neighborhood.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/command/build_ext.py", line 559, in build_extension
    target_lang=language)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_extend_utils_cffi.py", line 30, in <module>
    ffibuilder.compile(verbose=True)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/site-packages/cffi/api.py", line 727, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/site-packages/cffi/recompiler.py", line 1565, in recompile
    compiler_verbose, debug)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/nshimobayashi/anaconda3/envs/GIFT_2/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'x86_64-conda_cos6-linux-gnu-gcc' failed with exit status 1
`

**Comment by liuyuan-pal** [comment]
You may need to find a path "cuda_include" which contains "cuda_runtime.h" and a path "cuda_library" which contains "libcudart.so". 
It depends how you install the cuda library. 
In default, these two paths are "/usr/local/cuda/include" and "/usr/local/cuda/lib64".

**Comment by coper16** [comment]
I see...
Thanks!
I'll try it!!
